### ISSUE TITLE
Cambios en IndexedDB_controller

### ISSUE THREAD

**Issue by gorkang** [gorkang/jsPsychMaker#19]
Hay algunas diferencias importantes entre IndexedDB y MySQL

## CRITICAS

Cuando un usuario ya asignado retoma un protocolo, se dan estos dos problemas: 

- [x] A veces NO se cargan las tareas ya realizadas a tiempo!!! (VER LINEA ~590 indexedDB_controller.js). Se necesita un LEFT_JOIN o el equivalente ahi!
- [x] Error FONDECYT.js:95 Uncaught TypeError: Cannot read properties of undefined (reading '0') at FONDECYT.js:95. Esto ocurre en Chrome (no siempre), y no parece ocurrir en Firefox.

He puesto una secciones como la de abajo en indexedDB_controller.js para "arreglar" el problema. Si se comenta LONG_COMPUTATION, aparecen mucho mas frecuentemente los dos errores de arriba. Incluso con LONG_COMPUTATION, en el navegador de los monos (Chrome en docker) aparece el problema muy a menudo.
```
// DELETEME WHEN FIXED ----------------------
LONG_COMPUTATION = Array.from(Array(50000000).keys());
// END DELETEME ------------------------------
```

## OTRAS
- [x] Renombrar tablas IndexedDB (e.g. condition deberia ser user_condition?) para que usen los mismos nombres que las tablas MySQL
- [x] Linea 642 de mysql_controller.js usa Object.keys(between selection).length y 651 de indexedDB_controller.js usa condition_data.length. PQ la diferencia? condition_data.length parece mas bonita :)
- [x] clean_indexeddb es diferente. Falta DBtime, etc
- [x] La logica de algunas secciones de indexedDB_controller es distinta a la de MYSQL (por ejemplo Discarded Section in check_id too different (if (actual_user.status == "discarded") {)).  TODO lo posible en indexedDB_controller deberia ser IDENTICO a mysql_controller

**Comment by HeRm4nV** [comment]
We fixed all the points on V0.3 update (paring mysql_controller with indexeddb_controller)
