### ISSUE TITLE
Dos participantes asignados a la misma condicion al mismo tiempo

### ISSUE THREAD

**Issue by gorkang** [gorkang/jsPsychMaker#30]
Si dos participantes entran al mismo tiempo, el numero de asignados por condicion que leen es el mismo. Esto genera situaciones donde los dos son asignados a la misma condicion y el desequilibrio entre condiciones es > 1.

El proceso es:

- index.html [first screen]: check_id_status()  --> condition_selection() --> ASIGNACION de between_selection
- complete first task: saveData() --> completed_task_storage() --> WRITE to DB

Esto supone que si la persona 1 se pasa 10 minutos leyendo el consentimiento, durante esos 10 minutos tiene reservada esa condicion!

### Potencial solucion

Llamar a condition_selection() en completed_task_storage(), para la asignacion de between_selection en participantes nuevos.

De ese modo la asignacion de between_selection y WRITE to DB estaran juntas.

**Comment by HeRm4nV** [comment]
Se hizo el acercamiento más cercano con los cambios realizados, haciendo la menor cantidad de llamadas posibles antes de la seleccion para la asignacion de usuarios, los usuarios finales balancean la lista de condiciones en la recta final del experimento
