### ISSUE TITLE
Evaluación Plugin Survey Text

### ISSUE THREAD

**Issue by HeRm4nV** [gorkang/jsPsychMaker#40]
Se requiere re evaluar el plugin de survey-text por los cambios grandes que se le han hecho, por lo que hay que lanzar monos al compilado de tareas aceptadas actualmente para asegurarse que todas funcionan correctamente,

La nueva versión está actualmente en canonical_protocol_DEV/jsPsych-6/plugins/jspsych-survey-text.js

Una vez probada y validada habría que moverla al canonical protocol y al clean_canonical_protocol

**Comment by gorkang** [comment]
He lanzado un protocolo que incluye todas las pruebas que usan el plugin Survey Text:

secuentially_ordered_tasks_1 = ["DEMOGR",
  "DEMOGR12",
  "CRTv",
  "DEBRIEF",
  "OBJNUM",
  "BNT",
  "FORM4",
  "AIM",
  "CRT7",
  "FORM5",
  "DEMOGR3",
  "OTRASRELIG",
  "IDQ",
  "Report",
  "SDG"];

5 monos usando la version antigua y otros 5 con la version nueva. No hay ninguna diferencia en los DF_joined y DF_clean en ambos protocolos.

Parece que todo esta funcionando bien.

**Comment by HeRm4nV** [comment]
genial, lo damos por cerrado esto y pasamos el plugin al canonico entonces
