### ISSUE TITLE
NO se muestra error cuando no existe la carpeta .data/

### ISSUE THREAD

**Issue by gorkang** [gorkang/jsPsychMaker#41]
Si se lanza un protocolo online y  no existe la carpeta .data/, se puede avanzar sin problemas, pero los csv's con resultados NO se graban.

IMPORTANTE: Se deberia generar un ERROR para que no se pueda continuar.

**Comment by gorkang** [comment]
Tal vez algo asi deberia funcionar?

https://stackoverflow.com/questions/5425891/how-do-i-check-if-a-directory-exists-is-dir-file-exists-or-both

```
if ( !is_dir( $dir ) ) {
    mkdir( $dir );       
}
```

**Comment by HeRm4nV** [comment]
Fixed.

Now the system sends a request for files by php to the .data folder, if folder doesn't exists, then it is created
